# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d26d56cc8adcf3ee1a9fb3ec6ff26b70bc60435c9abc37bc79a4600b8cf350f2553cce884f4895278faa5f073ef80f5c4c0cc424b7794e7cd8c729675ea4afc0

test:
  secret_key_base: bcfb42c094440028b18c6b7e23cbd71bef742fc2fad20d2fd6ebecd52875b2d8b70fbbce4d36fa229a343cd9eabbc8f205a9d419c52f599c94dc8995692f1a6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
